//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nexos.DB.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int IdLibro { get; set; }
        public string Titulo { get; set; }
        public string Año { get; set; }
        public string Genero { get; set; }
        public string NumeroPaginas { get; set; }
        public int IdAutor { get; set; }
    
        public virtual Autor Autor { get; set; }
    }
}
